services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 3s
      timeout: 1s
      retries: 5

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    env_file:
      - .env
    healthcheck:
      test: 'echo lavalink'
      interval: 10s
      timeout: 10s
      retries: 3
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
      lavalink:
        condition: service_healthy
    env_file:
      - .env

volumes:
  db_data:
    driver: local
