services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ./main
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  db_data:
    driver: local
