services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 3s
      timeout: 1s
      retries: 5
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  lavalink:
      image: ghcr.io/lavalink-devs/lavalink:4
      container_name: lavalink
      restart: unless-stopped
      volumes:
      # mount application.yml from the same directory or use environment variables
      - ./application.yml:/opt/Lavalink/application.yml
      env_file:
        - .env
volumes:
  db_data:
    driver: local
