name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    # Navigate to the correct directory before verifying dependencies
    - name: Verify dependencies
      run: |
        cd uncord-bot-go
        go mod verify

    # Build the application
    - name: Build
      run: |
        cd uncord-bot-go
        go build ./cmd/main.go

    # Run go vet to catch issues
    - name: Run go vet
      run: |
        cd uncord-bot-go
        go vet ./...

    # Install golint for linting Go code
    - name: Install golint
      run: |
        cd uncord-bot-go
        go install golang.org/x/lint/golint@latest

    # Run golint to lint the code
    - name: Run golint
      run: |
        cd uncord-bot-go
        golint ./...

    # Run tests
    - name: Run tests
      run: |
        cd uncord-bot-go
        go test -race -vet=off ./...