name: Staging Deploy

on:
  push:
    branches:
      - main 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger deploy script on server via SSH
      continue-on-error: true
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.STAGING_SERVER_HOST }}
        username: ${{ secrets.STAGING_SERVER_USER }}
        key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
        script: |
          ~/deploy_app.sh
