name: Build and Deploy Discord Bot

on:
  push:
    branches:
      - main  # Change if you're using a different branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        username: ${{ secrets.PROD_SERVER_USER }}
        key: ${{ secrets.PROD_SERVER_SSH_KEY }}
        script: |
          ~/deploy_app.sh
